# This workflow will enable continuous deployment
name: CD

on:
  push:
    branches: [ development , master]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build image and deploy
      run: |
        if  docker ps -a | grep flask-python; then docker rm -f flask-python; fi
        docker build -t flask-image .
        docker run --name flask-python -p 5010:5010 flask-image:latest
      timeout-minutes: 5
  stop:
    runs-on: self-hosted

    steps:
      - name: Stop the container
        run: docker stop flask-python
