# This workflow will enable continuous deployment
name: CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        docker build -t flask-image .
        docker run --name flask-container -p 5010:5010 flask-image:latest
